# Generated by Django 4.2.2 on 2023-06-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('IdAutor', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Nacionalidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('IdLibro', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=60)),
                ('numPags', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('numUsuario', models.IntegerField()),
                ('nif', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('IdPrestamo', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('fecPrestamo', models.DateTimeField(blank=True, null=True)),
                ('fecDevolucion', models.DateTimeField(blank=True, null=True)),
                ('IdLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
